### ISSUE TITLE
Develop components in the react dashboard for remaining operations

### ISSUE THREAD

**Issue by agebeyaw** [yayawallet/react-dashboard#22]
@suraffy can you list out the missing features which are in the SDK but not available in the dashboard UI

**Comment by suraffy** [comment]
> @suraffy can you list out the missing features which are in the SDK but not available in the dashboard UI
- transferAsUser
- Saving
- Recurring Contract
- Equb
- Invitation

**Comment by suraffy** [comment]
### Equb Implementation Details
**Building components and Implement:** 
- creating an Equb
- Updating Equb
- Creating new round
- Equb payments
- LIst of Equbs
- Find Equb by user, ID, Name
- Find members of Equb
- Remove members of Equb
- Join Equb
- Leave Equb
